// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
		strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
	syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	res = -1;
res = syz_open_dev(0xc, 4, 0x15);
	if (res != -1)
		r[0] = res;
	res = syscall(__NR_dup2, r[0], r[0]);
	if (res != -1)
		r[1] = res;
*(uint16_t*)0x20000000 = 0x75;
*(uint16_t*)0x20000002 = 0xe4f;
*(uint16_t*)0x20000004 = 1;
	syscall(__NR_ioctl, r[1], 0x5609, 0x20000000ul);
	res = -1;
res = syz_open_dev(0xc, 4, 0x15);
	if (res != -1)
		r[2] = res;
*(uint8_t*)0x200001c0 = 2;
*(uint8_t*)0x200001c1 = 2;
*(uint16_t*)0x200001c2 = 2;
*(uint16_t*)0x200001c4 = 0x1f;
*(uint16_t*)0x200001c6 = 9;
*(uint16_t*)0x200001c8 = 9;
*(uint16_t*)0x200001ca = 0;
	syscall(__NR_ioctl, r[2], 0x541c, 0x200001c0ul);
	return 0;
}
