
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include "../../set_pid.h"
#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <unistd.h>

static uintptr_t syz_open_dev(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
    if (a0 == 0xc || a0 == 0xb) {
          char buf[128];
              sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
                              (uint8_t)a2);
                  return open(buf, O_RDWR, 0);
                    } else {
                          char buf[1024];
                              char* hash;
                                  strncpy(buf, (char*)a0, sizeof(buf));
                                      buf[sizeof(buf) - 1] = 0;
                                          while ((hash = strchr(buf, '#'))) {
                                                  *hash = '0' + (char)(a1 % 10);
                                                        a1 /= 10;
                                                            }
                                              return open(buf, a2, 0);
                                                }
}

static void test();

void loop()
{
    while (1) {
          test();
            }
}

uint64_t r[1] = {0xffffffffffffffff};
void test()
{
    long res;
      memcpy((void*)0x20000080, "/dev/sg#", 9);
        res = syz_open_dev(0x20000080, 0, 0);
          if (res != -1)
                r[0] = res;
            memcpy((void*)0x200006c0, "\x00\x04\x00\x00\x00\x00\x00\x00\x15\xf2\xda\x82"
                                            "\x89\x9a\x54\xac\xab\x08\x00\x00\x34\x3c\x7d\x71"
                                                                        "\xb2\x28\xc3\xf9\x39\x7a",
                                                                                 30);
              syscall(__NR_ioctl, r[0], 1, 0x200006c0);
}

int main()
{
set_pid();
    syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
      for (;;) {
            loop();
              }
}

